datamodule:
  name: justraigs
  args:
    data_dir: data/JustRAIGS
    task: multilabel
    batch_size: 16
    dataset: justraigs
    test_split: 0.01
    val_split: 0.2
    use_cropped: True
    use_nan: True
    positives_only: True
    num_workers: 10

trainer:
  args:
    max_epochs: 1000
    log_step: 20
    save_metric: ham_dist

criterion: bce_logits_loss

optimizer: 
  name: adam
  args:
    lr: 0.001

# resume_path: wandb/run-20240416_201713-spkdgo3b/files/mobilenetv3_small_050.lamb_in1k_ham_dist_0.1592_just.pt
model:
  name: just_extraction
  args:
    model_path: submission/models/densenet201_sens_at_spec_0.9183_ref.pt
    num_classes: 10
    scriptable: True
    freeze: False
    custom_head: False

scheduler:
  name: reduce_on_plateau
  args:
    patience: 10

monitor:
  project_name: raigs-glaucoma
  # mode: 'offline'
  # Optional arguments.
  # entity: kris
  # job_name: experiment

metrics:
  train:
    - f1_score:
        validate_args: False # OBRIGATÓRIO PARA ACEITAR NaN NAS LABELS
        average: macro
    - specificity:
        validate_args: False
        average: macro
    - recall:
        validate_args: False
        average: macro
    - precision:
        validate_args: False
        average: macro
    - ham_dist:
        validate_args: False
        average: macro
  val:
    - f1_score:
        validate_args: False # OBRIGATÓRIO PARA ACEITAR NaN NAS LABELS
        average: macro
    - specificity:
        validate_args: False
        average: macro
    - recall:
        validate_args: False
        average: macro
    - precision:
        validate_args: False
        average: macro
    - ham_dist:
        validate_args: False
        average: macro
    - conf_matrix:
        validate_args: False

transforms:
  - name: Equalize
    args:
      by_channels: False
  - name: ShiftScaleRotate
    args:
      shift_limit: 0.1
      scale_limit: 0
      rotate_limit: 4
      interpolation: 2
      border_mode: 
      p: 0.6
  - name: RandomCropFromBorders
    args:
      crop_left: 0.3
      crop_right: 0.3
      crop_top: 0.6
      crop_bottom: 0.3
      p: 0.6
  - name: RGBShift
    args:
      r_shift_limit: 3
      g_shift_limit: 3
      b_shift_limit: 3
      p: 0.6
  - name: RandomBrightnessContrast
    args:
      brightness_limit: 0.3
      contrast_limit: 0.3
      p: 0.6
  - name: GaussNoise
    args:
      p: 0.6
  - name: Defocus
    args:
      p: 0.6
  - name: HorizontalFlip
    args:
      p: 0.6
  - name: Resize
    args:
      height: 106
      width: 106
      interpolation: 2
  - name: Normalize
    args:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]



seed: 42